
import com.google.gson.GsonBuilder;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
//import static noobClass.blockchain;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oluwaseun
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        detailsGen dg = new detailsGen();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nextofkin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        signup_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pension-Padi");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 100, 148));
        jPanel2.setName("side_panel"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(36, 123, 160));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up New Worker");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 287, 240, 70));

        jLabel2.setBackground(new java.awt.Color(27, 152, 224));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 70));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("x");
        jLabel12.setAlignmentY(0.0F);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 41, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 650));

        jPanel3.setBackground(new java.awt.Color(232, 233, 232));
        jPanel3.setName("main_panel"); // NOI18N
        jPanel3.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(232, 241, 242));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/pension-pad.jpg"))); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(home, "card3");

        signup.setBackground(new java.awt.Color(232, 241, 242));
        signup.setName("home"); // NOI18N
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCalendar2.setBackground(new java.awt.Color(36, 123, 160));
        jCalendar2.setForeground(new java.awt.Color(204, 204, 204));
        jCalendar2.setDecorationBackgroundColor(new java.awt.Color(36, 123, 160));
        jCalendar2.setDecorationBackgroundVisible(false);
        jCalendar2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jCalendar2.setInheritsPopupMenu(true);
        jCalendar2.setTodayButtonVisible(true);
        jCalendar2.setWeekOfYearVisible(false);
        jCalendar2.setWeekdayForeground(new java.awt.Color(204, 204, 204));
        signup.add(jCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 390, 160));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Name");
        signup.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, 30));

        name.setBackground(new java.awt.Color(220, 213, 213));
        name.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setToolTipText("Enter the workers name");
        name.setBorder(null);
        signup.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 460, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Date Of Birth");
        signup.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, 30));

        dob.setBackground(new java.awt.Color(220, 213, 213));
        dob.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 0, 0));
        dob.setToolTipText("Enter the workers name");
        dob.setBorder(null);
        signup.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 460, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Next Of Kin");
        signup.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, 30));

        nextofkin.setBackground(new java.awt.Color(220, 213, 213));
        nextofkin.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        nextofkin.setForeground(new java.awt.Color(0, 0, 0));
        nextofkin.setToolTipText("Enter the workers name");
        nextofkin.setBorder(null);
        signup.add(nextofkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 460, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contact");
        signup.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 160, 30));

        contact.setBackground(new java.awt.Color(220, 213, 213));
        contact.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        contact.setForeground(new java.awt.Color(0, 0, 0));
        contact.setToolTipText("Enter the workers name");
        contact.setBorder(null);
        signup.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 460, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Date Of Appointment");
        signup.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 160, 30));

        email.setBackground(new java.awt.Color(220, 213, 213));
        email.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setToolTipText("Enter the workers name");
        email.setBorder(null);
        signup.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 280, 30));

        email1.setBackground(new java.awt.Color(220, 213, 213));
        email1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(0, 0, 0));
        email1.setToolTipText("Enter the workers name");
        email1.setBorder(null);
        signup.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 460, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("E-mail");
        signup.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 160, 40));

        email2.setBackground(new java.awt.Color(220, 213, 213));
        email2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        email2.setForeground(new java.awt.Color(0, 0, 0));
        email2.setToolTipText("Enter the workers name");
        email2.setBorder(null);
        signup.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 460, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Level");
        signup.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 160, 30));

        salary.setBackground(new java.awt.Color(220, 213, 213));
        salary.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        salary.setForeground(new java.awt.Color(0, 0, 0));
        salary.setToolTipText("Enter the workers name");
        salary.setBorder(null);
        signup.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 460, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Salary");
        signup.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 30));

        signup_btn.setBackground(new java.awt.Color(36, 123, 160));
        signup_btn.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        signup_btn.setForeground(new java.awt.Color(255, 255, 255));
        signup_btn.setText("Sign Up");
        signup_btn.setBorder(null);
        signup_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_btnMouseClicked(evt);
            }
        });
        signup.add(signup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 592, 140, 40));

        jButton2.setText("Pick Date");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        signup.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 450, 160, -1));

        jPanel3.add(signup, "card2");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -10, 940, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
     Object[] options = {"Leave","Stay"};
int op = JOptionPane.showOptionDialog(this,"Leaving so soon? Do you really wanna leave?",
            "Exit Pension-Padi?",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.DEFAULT_OPTION,
            null,
            options,
            options[1]);
      if(op == 0){  
      System.exit(0);}
      else{
      
      }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        signup.setVisible(true);
        home.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        home.setVisible(true);
        signup.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        if (jCalendar2.isVisible()){
            jCalendar2.setVisible(false);
        }
        else{
            jCalendar2.setVisible(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked
        /**
         * populate the array list with details from the form 
         * @param evt 
         */
        private List<String> myData = new ArrayList<>();
    private void signup_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_btnMouseClicked
        /**
         * a method to collect all data from the user sign up page and store it in an array list
         * @return array list containing user details
         */
        
        
         myData.add(name.getText());
         myData.add(contact.getText());
         myData.add(email.getText());
         myData.add(dob.getText());
         myData.add(email2.getText());
         
         String blockchainJson = new GsonBuilder().setPrettyPrinting().create().toJson(myData);
         System.out.println(blockchainJson);
    }//GEN-LAST:event_signup_btnMouseClicked
        public List<String> getMyData(){
            return myData;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField email2;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nextofkin;
    private javax.swing.JTextField salary;
    private javax.swing.JPanel signup;
    private javax.swing.JButton signup_btn;
    // End of variables declaration//GEN-END:variables
}
